# Generated by Django 2.1.1 on 2020-01-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20200114_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='posts',
            field=models.ManyToManyField(blank=True, to='myblog.Post'),
        ),
    ]
